# Generated by Django 5.0.4 on 2024-04-07 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile_address_profile_personal_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='personal_number',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='work_number',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
